### ISSUE TITLE
Does not identify nested repositories.

### ISSUE THREAD

**Issue by da1nerd** [giuseongit/rf#1]
This is a rare use case, but it's possible to have repositories nested inside of each other. For example, when using [meta](https://github.com/mateodelnorte/meta).

Nice job on this tool. I already love it!

**Comment by giuseongit** [comment]
Well yes, it should be quite simple to implement that, but my fear is that the application could detect unwantend repository. I've not yet come with a solution about this

**Comment by da1nerd** [comment]
you could potentially introduce a configuration that controls how deep to search within a repository. The default could be 0 (just the top level repository. It could look for `~/rf.rc` to load a custom depth.

**Comment by giuseongit** [comment]
Great! There is already a configuration object that handles serialization quote easy, it should be easy to implement this thing. I'll do as soon as I've got some time!

**Comment by giuseongit** [comment]
@neutrinog just implemented, can you do a quick review to this pr?@neutrinog

**Comment by giuseongit** [comment]
feature implemented

**Comment by da1nerd** [comment]
Just leaving a note here for posterity. If you previously ran the code it will now break because the config file is missing a required field. So you need to add `subrepository_depth: 1` in `~/.config/rf/rf.yml` in order to get the default settings working.

Otherwise, the update works as expected!
